version: "3"

services:
  ##########################
  ### SETUP SERVER CONTAINER
  ##########################
  server:
    # Tells docker-compose which image to pull from docker hub
    image: tiportero/portero_web_server:latest
    environment:
      - MONGO_URI=mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@${MONGO_URI}
      - PORT=${PORT}
      - NODE_ENV=${NODE_ENV}
    ports:
      - ${PORT}:${PORT}
    volumes:
      - ./client-files:/clients
      - ./insurance-files:/insurances
      - ./sinester-files:/sinesters
    command: node src/server.js
    links:
      - db
    restart: always
  ##########################
  ### SETUP CLIENT CONTAINER
  ##########################
  client:
    image: tiportero/portero_web_client:latest
    ports:
      - 80:8080
      - 35729:35729
    links:
      - server
    restart: always
  ##########################
  ### SETUP DB CONTAINER
  ##########################
  db:
    image: mongo:latest
    command: mongod --port 25575
    ports:
      - 25575:25575
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container: